name: Keep Render App Active

on:
  schedule:
    - cron: '*/14 * * * *'

jobs:
  keep-app-active:
    runs-on: ubuntu-latest

    steps:
    - name: Install curl
      run: sudo apt-get install -y curl

    - name: Send Keep-Alive Request with Retry
      run: |
        retries=5
        delay=10
        url="http://qr-code-generator-ksbv.onrender.com"
        for i in $(seq 1 $retries); do
          echo "Attempt $i"
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null "$url")
          if [ $response -eq 200 ]; then
            echo "Successfully reached the app."
            exit 0
          fi
          echo "Failed to reach the app. Waiting $delay seconds before retrying..."
          sleep $delay
        done
        echo "Failed to reach the app after $retries attempts."
        exit 1
